### ISSUE TITLE
Combine efforts with SIMDe?

### ISSUE THREAD

**Issue by nemequ** [AlexYaruki/iris#1]
I just found this project, and it's quite similar to one of my own, [SIMDe](https://github.com/nemequ/simde).  It seems a shame to duplicate efforts, I was wondering if you might be interested in combining them.

There are some significant differences.  SIMDe is MIT licensed, and written in C (though usable from C++).

SIMDe has complete implementations of several Intel ISA extensions but NEON is almost nonexistent.  AFAICT this would complement Iris pretty well since your NEON support seems to be pretty far along but Intel looks pretty limited.

**Comment by AlexYaruki** [comment]
Glad to hear that not only me thinks there is need to such solution. 

I will look through your project and get back to you.

**Comment by AlexYaruki** [comment]
Oh, I only know see that it is C project. 
Main reason I started this project was to use C++ as implementation language. Netherless I will look at it.

**Comment by nemequ** [comment]
Technically the implementation is also C++; it uses a subset of C which is compatible with C++.  But yes, it's basically C.

If you want to write in idiomatic C++ then the projects will have to remain separate since I'm not willing to drop support for C.  On the other hand, if what you care about is that it's usable from C++, SIMDe is.  For example, [here](https://github.com/nemequ/leopard/tree/simde) is a port of a C++ project to SIMDe.

**Comment by AlexYaruki** [comment]
As I said earlier, project was and will be written in C++. Besides, maybe in the future, I could come up with improvements specific to C++. C lacks a lot of features that are useful for me.
